on:
  push:
    branches:
      - test

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Job 1
      id: job1
      uses: jeff-vincent/example-composite-action@test
    outputs:
      random-number: ${{ steps.job1.outputs.random-number }}
        
        
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Job 2
      id: job2
      run: |
        echo "${{ needs.job1.outputs.random-number }}"
