on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: jeff-vincent/example-composite-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
    outputs:
      random-number: ${{ steps.foo.outputs.random-number }}
        
  second_job:
    needs: hello_world_job
#     runs-on: macOS-latest
#     name: A second job
#     steps:
#       - id: bar
#       - run: echo ${{ needs.hello_world_job.outputs.random-number }}

      
      
