on:
  push:
    branches:
      - test

jobs:
  job1:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: foo
      - run: echo random-number $RANDOM
        shell: bash

      
      
  job2:
    needs: job1
    runs-on: ubuntu-latest
    name: random number
    steps:
      - id: bar
      - run: echo random-number $RANDOM
        shell: bash
      
